### PR TITLE
Unit testing (PHPUnit)

### PR DESCRIPTION
**Pull request by DrDelay**
[#112](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/130#issuecomment-241246519) got me thinking that unit tests wouldn't be a bad thing to have.

This contains the basic setup along with tests for:
- `Pokemon::isDeployed()`
- `Pokemon::canEvolve()`
- `Pokemon::canUpgrade()`

*(Tell me if I did things wrong with the mocks)*

### CODE REVIEW

**Comment by f2008305** [comment]
src/Api/Pokemon/Support/PokemonDetailsTrait.php
update this:
` if ($this->getCandies()->getCount() < $data->getCandyToEvolve()) {`
to this:
` if ($data->getCandyToEvolve()>0 && $this->getCandies()->getCount() < $data->getCandyToEvolve()) {`

**Comment by NicklasWallgren** [comment]
Clean use of generators and data providers 👍 . I really want one of those Abras on steroids ;)

**Comment by f2008305** [comment]
ah right, what about the new attacks introduced by niantic this night?

**Comment by NicklasWallgren** [comment]
@f2008305 Feel free to update the https://github.com/NicklasWallgren/PokemonGoAPI-PHP/blob/master/src/Api/Pokemon/Data/PokemonMetaRegistry.php with the latest changes.

**Pull request merged**
