### PR TITLE
Install via composer repository guide

### PR DESCRIPTION
**Pull request by Omanyte**
Just change the "Build" heading the the README.md to "Install" with instruction on how to install as a composer package without being on Packagist. I believe most devs who are willing to work on this package would know how to "Build" the app although some may be unaware how to install as a package without it being on Packagist.

### CODE REVIEW

**Comment by DrDelay** [comment]
Can you please add the `prefer-stable` property? I think this should always be there if you define a custom stability.

**Comment by NicklasWallgren** [comment]
Thanks, but wouldn't it be easier to just require the composer package :)

`composer require nicklasw/pkm-go-api `

**Comment by Omanyte** [comment]
Yes you are quite right, I didn't see it on Packagist because I search for "NicklasWallgren" and "PokemonGoAPI-PHP" neither of which bring up anything. I will modify my pull request when I get home.

**Comment by Omanyte** [comment]
Amended

**Pull request merged**
