### PR TITLE
Add PhpStorm IDE/PHPUnit gitignore entries

### PR DESCRIPTION
**Pull request by DrDelay**
I always have to be careful as `git add .` would add the *.idea* directory of my IDE :laughing:

### CODE REVIEW

**Comment by NicklasWallgren** [comment]
Wouldn't it be better to add it to your local ".git/info/exclude" file? Since it's specific to your development environment :)

**Comment by DrDelay** [comment]
Works ofcourse, I just thought PhpStorm is quite common ^^

**Comment by Ni42** [comment]
If this was a vote, I would agree on adding .idea to it, too ;)

**Comment by mattwells** [comment]
You can globally ignore your dev files from git: http://stackoverflow.com/a/7335487

**Pull request merged**
